version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: bluescript_server
    volumes:
      - ./server:/bluescript/server
      - /bluescript/server/node_modules
      - ./modules:/bluescript/modules
      - ./microcontroller:/bluescript/microcontroller
      - ./benchmarks:/bluescript/benchmarks
    working_dir: /bluescript/server
    command: npm run server
    ports:
      - "8080:8080"

  notebook:
    build:
      context: .
      dockerfile: notebook.Dockerfile
    container_name: bluescript_notebook
    volumes:
      - ./notebook:/notebook
      - /notebook/node_modules
    working_dir: /notebook
    command: npm start
    ports:
      - "3000:3000"
