name: esp32 port

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "microcontroller/core/**"
      - "microcontroller/ports/esp32/**"
      - "modules/esp32/**"

jobs:
  build_idf:
    name: Build microcontroller/ for ESP32
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build runtime for ESP32
        run: docker run --rm -v $PWD:/project -w /project/microcontroller/ports/esp32 -u $UID -e HOME=/tmp espressif/idf:release-v5.0 idf.py build
