name: Create and Upload Release ZIP

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    name: Build and Upload ZIP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP of 'microcontroller' directory
        run: zip -r release-microcontroller-${{ github.ref_name }}.zip microcontroller

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-microcontroller-${{ github.ref_name }}.zip
          asset_name: release-microcontroller-${{ github.ref_name }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}